version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./model:/app/model
      - ./temp:/app/temp
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your-secret-key-here
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5000
    depends_on:
      - backend
    restart: unless-stopped 